### ISSUE TITLE
t/kernel_release.t fails (on non-Ubuntu systems?)

### ISSUE THREAD

**Issue by eserte** [glasswalk3r/Linux-Info#10]
t/kernel_release.t fails on some of my smoker systems like this:
```
#   Failed test 'get_major returns the expected value'
#   at t/kernel_release.t line 24.
#          got: '13'
#     expected: '0'
# Looks like you failed 1 test of 15.
t/kernel_release.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/15 subtests 
```

It seems that this happens on non-Ubuntu systems (debian, fedora, centos).

**Comment by glasswalk3r** [comment]
Thanks for reporting. Looks like a conditional test (which doesn't make any sense, so it's probably something I forgot to remove before releasing).

**Comment by glasswalk3r** [comment]
PR #11 should fix this

**Comment by glasswalk3r** [comment]
Fixed and released to CPAN.
