### ISSUE TITLE
sysinfo init mode

### ISSUE THREAD

**Issue by sparvu** [glasswalk3r/Linux-Info#2]
Take a look:

```
use strict;
use warnings;
use Linux::Info;

my $lxs  = Linux::Info->new( sysinfo => 1 );
my $stat = $lxs->get;
```

this wil return:

```
Linux::Info: invalid option 'sysinfo' at ./hdwrec3 line 7.
```

This was working ok under S::S::L original perl module.

**Comment by glasswalk3r** [comment]
This is not an issue and it is documented too, see http://search.cpan.org/~arfreitas/Linux-Info-1.1/lib/Linux/Info.pm#OPTIONS.
SysInfo is not a "statistics" module: you don't need to create instances of it over time to later make comparisons with them (as to calculate load averages, for example).

**Comment by sparvu** [comment]
right. please fix this part on the documentation since this wont work

```
    use Linux::Info;

    my $lxs = Linux::Info->new(
        sysinfo   => 1,
        cpustats  => 1,
        procstats => 1,
        memstats  => 1,
        pgswstats => 1,
        netstats  => 1,
        sockstats => 1,
        diskstats => 1,
        diskusage => 1,
        loadavg   => 1,
        filestats => 1,
        processes => 1,
    );

    sleep 1;
    my $stat = $lxs->get;
```

http://search.cpan.org/~arfreitas/Linux-Info-1.2/lib/Linux/Info.pm

**Comment by glasswalk3r** [comment]
Oh, thanks for reporting that. I've being doing some additional fixes on the Pod, just fixed that as well. For now, at least you should get a nice error message telling you not to do that. Next release will include this.
